# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Homepage of Haoran Xu
description: >- # this means to ignore newlines until "baseurl:"
  This is Homepage of Haoran Xu from Xidian University.
baseurl: "/bay" # the subpath of the site
url: "https://ryanxhr.github.io" # the base hostname & protocol for the site
og_image: /assets/img/hoyin.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: Projects

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: ryanxhr@gmail.com
      link: mailto:ryanxhr@gmail.com
    - name: WeChat
      value: YourWeChatUsername
      link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/ryanxhr
      username: "@ryanxhr"
    - name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://www.linkedin.com/in/haoran-xu-b6a487153/
    - name: GitHub
      link: http://github.com/ryanxhr
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - name: RSS
#      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
